# Generated by Django 3.2.17 on 2023-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_pi',
            field=models.BooleanField(default=False, verbose_name='是否为项目负责人'),
        ),
    ]
