# Generated by Django 3.2.17 on 2023-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectattribute',
            name='value',
            field=models.CharField(max_length=128, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='historicalprojectattributeusage',
            name='value',
            field=models.FloatField(default=0, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='projectattribute',
            name='value',
            field=models.CharField(max_length=128, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='projectattributeusage',
            name='value',
            field=models.FloatField(default=0, verbose_name='金额'),
        ),
    ]
