# Generated by Django 3.2.17 on 2023-03-27 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_selectable', models.BooleanField(default=True, verbose_name='可选性')),
                ('description', models.CharField(max_length=255, verbose_name='学科描述')),
                ('fos_nsf_id', models.IntegerField(blank=True, null=True, verbose_name='NSF编号')),
                ('fos_nsf_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='NSF缩写')),
                ('directorate_fos_id', models.IntegerField(blank=True, null=True, verbose_name='管理机构ID')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_of_science.fieldofscience', verbose_name='父学科ID')),
            ],
            options={
                'verbose_name': '学科领域',
                'verbose_name_plural': '学科领域',
                'ordering': ['description'],
            },
        ),
    ]
