# Generated by Django 3.2.17 on 2023-04-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='resources',
            field=models.ManyToManyField(to='resource.Resource', verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationstatuschoice', verbose_name='状态'),
        ),
        migrations.AlterUniqueTogether(
            name='allocationuser',
            unique_together={('user', 'allocation')},
        ),
    ]
